name: CD
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

env:
  RELEASE_NOTES_ARTIFACT_SUFFIX: release-notes.md
  CLICOLOR: 1

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  release-notes:
    runs-on: ubuntu-latest
    needs:
      - checks
    if: ${{ needs.checks.outputs.charts != '[]' }}
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.checks.outputs.charts) }}
    env:
      CHANGELOG_FILE: ${{ matrix.chart.path }}/CHANGELOG.md
      RELEASE_NOTES_FILE: ${{ matrix.chart.path }}/RELEASE.md
    steps:
      - name: Checkout chart's changelog
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.CHANGELOG_FILE }}
      - name: Extract chart's release notes
        uses: eaasi/release-notes-action@v0.6
        with:
          changelog-file: ${{ env.CHANGELOG_FILE }}
          release-notes-file: ${{ env.RELEASE_NOTES_FILE }}
          release-version: '${{ matrix.chart.version }}'
      - name: Upload extracted release notes
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.chart.name }}-${{ env.RELEASE_NOTES_ARTIFACT_SUFFIX }}
          path: ${{ env.RELEASE_NOTES_FILE }}

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - checks
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: ./configs/chart-releaser.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
