name: CD
on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

env:
  RELEASE_NOTES_ARTIFACT_SUFFIX: release-notes.md
  CLICOLOR: 1

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  release-notes:
    runs-on: ubuntu-latest
    needs:
      - checks
    if: ${{ needs.checks.outputs.charts != '[]' }}
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.checks.outputs.charts) }}
    env:
      CHANGELOG_FILE: ${{ matrix.chart.path }}/CHANGELOG.md
      RELEASE_NOTES_FILE: ${{ matrix.chart.path }}/RELEASE.md
      RELEASE_NOTES_FILENAME: RELEASE.md
    steps:
      - name: Checkout chart's changelog
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.CHANGELOG_FILE }}
      - name: Extract chart's release notes
        uses: eaasi/release-notes-action@v0.6
        with:
          changelog-file: ${{ env.CHANGELOG_FILE }}
          release-notes-file: ${{ env.RELEASE_NOTES_FILE }}
          release-version: '${{ matrix.chart.version }}'
      - name: Upload extracted release notes
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.chart.name }}-${{ env.RELEASE_NOTES_ARTIFACT_SUFFIX }}
          path: |
            # NOTE: using a glob to preserve path!
            **/${{ env.RELEASE_NOTES_FILENAME }}

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs:
      - checks
      - release-notes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure Git
        run: |
          git config user.name "${{ github.event.pusher.name }}"
          git config user.email "${{ github.event.pusher.email }}"
      - name: Install Just
        uses: taiki-e/install-action@v2
        with:
          tool: just
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.0
      - name: Add external chart repositories
        run: just add-chart-repos
      - name: Download prepared release notes
        uses: actions/download-artifact@v5
        with:
          pattern: '*${{ env.RELEASE_NOTES_ARTIFACT_SUFFIX }}'
          merge-multiple: true
      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        with:
          config: ./configs/chart-releaser.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
