name: checks
on:
  workflow_call:

permissions:
  contents: read

env:
  CLICOLOR: 1
  RUST_BACKTRACE: 1

jobs:
  commit-style:
    runs-on: ubuntu-latest
    steps:
      - id: commit-range
        name: Determine commit range
        uses: eaasi/commit-range-action@v0.5
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Run commit style linter
        uses: crate-ci/committed@v1.1.5
        with:
          args: -v --config ./configs/committed.toml ${{ env.COMMITTED_ARGS }}
          commits: ${{ steps.commit-range.outputs.commit-range }}
        env:
          # Disallow merge commits to be present in pull-requests
          COMMITTED_ARGS: ${{ (github.event_name == 'pull_request') && '--no-merge-commit' || '' }}

  spelling:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Run spell checker
        uses: crate-ci/typos@v1.29.7
        with:
          config: ./configs/typos.toml

  validation:
    runs-on: ubuntu-latest
    env:
      CHART_TESTING_LOG: chart-testing.log
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch whole history if workflow was triggered by a pull-request
          fetch-depth: ${{ (github.event_name == 'pull_request') && 0 || 1 }}
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.0
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          check-latest: true
      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Run chart linters and validators
        run: ct lint --config ./configs/chart-testing.yaml ${{ env.CHART_TESTING_ARGS }} | tee ${{ env.CHART_TESTING_LOG }}
        env:
          # Enable change detection if workflow was triggered by a pull-request, else check all charts
          CHART_TESTING_ARGS: ${{ (github.event_name == 'pull_request') && '--target-branch main' || '--all' }}
      - id: ct-log-parser
        name: Parse chart-testing logs
        uses: eaasi/chart-list-action@v0.3
        with:
          ct-log-file: ${{ env.CHART_TESTING_LOG }}

  testing:
    runs-on: ubuntu-latest
    needs:
      - spelling
      - validation
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Start Minikube cluster
        uses: medyagh/setup-minikube@v0.0.20
        with:
          start-args: '--namespace eaasi'
          cpus: 'no-limit'
          memory: 'no-limit'
          wait: 'apiserver,system_pods'
      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.17.0
      - name: Install chart-testing
        uses: helm/chart-testing-action@v2.7.0
      - name: Install and test charts
        run: ct install --config ./configs/chart-testing.yaml --all
