name: CI
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml
