name: CI
on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: read

jobs:
  checks:
    uses: ./.github/workflows/checks.yaml

  changelog:
    runs-on: ubuntu-latest
    needs:
      - checks
    if: ${{ needs.checks.outputs.charts != '[]' }}
    strategy:
      matrix:
        chart: ${{ fromJSON(needs.checks.outputs.charts) }}
    env:
      CHANGELOG_FILE: ${{ matrix.chart.path }}/CHANGELOG.md
    steps:
      - name: Checkout chart's changelog
        uses: actions/checkout@v4
        with:
          sparse-checkout: ${{ env.CHANGELOG_FILE }}
      - id: release-notes-checker
        name: Check chart's changelog
        uses: eaasi/release-notes-action@v0.6
        continue-on-error: true
        with:
          changelog-file: ${{ env.CHANGELOG_FILE }}
          release-version: '${{ matrix.chart.version }}'
      - name: Warn if chart's changelog is incomplete
        if: ${{ steps.release-notes-checker.outcome != 'success' }}
        run: echo "::warning ::No release notes for v${{ matrix.chart.version }} found!"
